### ISSUE TITLE
Compiling 6.2

### ISSUE THREAD

**Issue by AndreiAdii** [JMBQ/Honkai-Impact-3-mod#9]
Compiling version 6.2 with the Mod is not working anymore (6.1 is working, 6.2 no). I tried multiple compilers.

**Comment by JMBQ** [comment]
Please provide logging

**Comment by AndreiAdii** [comment]
Sorry for being late, here is the log:
---
java version "1.8.0_351"
Java(TM) SE Runtime Environment (build 1.8.0_351-b10)
Java HotSpot(TM) Client VM (build 25.351-b10, mixed mode, sharing)
File or folder does not exist
---------------------------

Decompiling APK file... (Press ESC to cancel)
Command: java.exe  -jar "C:\Users\Meow\Downloads\APK Easy\Apktool\apktool_2.6.1.jar" d -f --only-main-classes -o "C:\Users\Meow\Downloads\APK Easy\1-Decompiled APKs\20221130-122127-global_android_sim-Global-v6_2-final-277a0ec45b1d-3969-6.2.0-ASB-Win108-Agent2-1195" "C:\Users\Meow\Downloads\20221130-122127-global_android_sim-Global-v6_2-final-277a0ec45b1d-3969-6.2.0-ASB-Win108-Agent2-1195.apk"

I: Using Apktool 2.6.1 on 20221130-122127-global_android_sim-Global-v6_2-final-277a0ec45b1d-3969-6.2.0-ASB-Win108-Agent2-1195.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Meow\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
Decompile successful.
---------------------------

Compiling APK file... (Press ESC to cancel)
Command: java.exe -jar "C:\Users\Meow\Downloads\APK Easy\Apktool\apktool_2.6.1.jar" b -f --use-aapt2 -o "C:\Users\Meow\Downloads\APK Easy\2-Recompiled APKs\20221130-122127-global_android_sim-Global-v6_2-final-277a0ec45b1d-3969-6.2.0-ASB-Win108-Agent2-1195.apk" "C:\Users\Meow\Downloads\APK Easy\1-Decompiled APKs\20221130-122127-global_android_sim-Global-v6_2-final-277a0ec45b1d-3969-6.2.0-ASB-Win108-Agent2-1195"

I: Using Apktool 2.6.1
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroidx/annotation/InspectableProperty$ValueType;->values()[Landroidx/annotation/InspectableProperty$ValueType;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1047)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:346)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:301)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:430)
	at brut.androlib.Androlib.buildSources(Androlib.java:361)
	at brut.androlib.Androlib.build(Androlib.java:313)
	at brut.androlib.Androlib.build(Androlib.java:280)
	at brut.apktool.Main.cmdBuild(Main.java:255)
	at brut.apktool.Main.main(Main.java:82)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1320)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1043)
	... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65536
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1280)
	... 11 more

Compile failed.
---
I tried compiling 6.2 version of the game with the changes, it failed like above.
I tried compiling 6.2 version of the game with no changes made to package, it worked.
I tried compiling 6.1 version of the game with changes, it worked.

**Comment by JMBQ** [comment]
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65536
This means that the number of methods in the current dex is full and requires dex subpackaging.
If you use apkEasyTools, then I can tell you an easy way to do it, open the decompile directory, check if there is a directory with a name like smali_classes2, then create a new folder and rename it to smali_classes3, in short you have to make sure it must be +1. If smali_classes3 already exists If smali_classes3 already exists, then change it to smali_classes4, and so on, and put my smali files into this new folder, not into the one shown in my picture, other steps remain the same

**Comment by AndreiAdii** [comment]
It worked, thanks, problem solved
